
name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'backend_app/**'
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend_app

    permissions:
      contents: 'read'
      id-token: 'write'  # Required for Workload Identity Federation#

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Auth gcloud
        uses: google-github-actions/auth@v3
        with:
          #credentials_json: ${{secrets.GCP_KEY}}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'

      - name: Build and Deploy to Cloud Run
        run: |
          gcloud builds submit --tag ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/${{ secrets.GCR_SERVICE_NAME }}:latest
          gcloud run deploy ${{ secrets.GCR_SERVICE_NAME }} \
            --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/${{ secrets.GCR_SERVICE_NAME }}:latest \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated

      # - name: Configure Docker
      #   run: |
      #     gcloud auth configure-docker  ${{ secrets.GCP_REGION }}-docker.pkg.dev

      # - name: Build and Push Docker Image
      #   run: |
      #     docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/fastapi-service:latest -f Dockerfile .
      #     docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/fastapi-service:latest

      # - name: Deploy to Cloud Run
      #   run: |
      #     gcloud run deploy fastapi-service \
      #       --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/fastapi-service:latest \
      #       --platform managed \
      #       --region us-east1 \
      #       --allow-unauthenticated

